### ISSUE TITLE
Logo Requests

### ISSUE THREAD

**Issue by dweee** [kbuffington/georgia-image-packs#1]
Hi, I know this repo doesn't have more attention but I thought it'd be a good idea to have an issue thread dedicated to sharing more images that aren't in the packs already?

To kick it off, I'd like Ed Banger Records to be included in the next update. The best Public Domain image I could find was on their Wikipedia page ([image](https://en.wikipedia.org/wiki/Ed_Banger_Records#/media/File:Ed_Banger_Records.jpg)).

**Comment by kbuffington** [comment]
Hey, I can get that added for you, but the best way to do it is submit it yourself at https://fanart.tv. You'll have to follow their conventions (400x270 .png with at least a slight dropshadow) but once it gets approved I make sure to include every record label they have in my image packs. I've done about a third of the labels they've got at fanart.tv, so I have some experience with the process.

**Comment by kbuffington** [comment]
Well, I screwed up and didn't do this when I refreshed the image packs last night. It'll be in the December or January update.

You can manually download it yourself here though: 
https://fanart.tv/bigpreview/labels/9cdc4159-ec50-47f0-a7a2-e107618d5246/musiclabel/ed-banger-records-5bde81914c041.png
